# Configuration for welcome - https://github.com/behaviorbot/welcome

# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome

newIssueWelcomeComment: >
  Hello there! ğŸ‘‹


  Thank you and congratulations ğŸ‰ for opening your very first issue in this project! ğŸ’–


  In case you want to claim this issue, please comment down below! We will try to get back to you as soon as we can. ğŸ‘€

newPRWelcomeComment: >
  Hello there! ğŸ‘‹
  

  Thank you and congrats ğŸ‰ for opening your first PR on this project! âœ¨ ğŸ’–


  We will try to review it soon!
  