kafka:
  clusters:
    - name: local
      bootstrapServers: b-1.kad-msk.57w67o.c6.kafka.eu-central-1.amazonaws.com:9094
      properties:
        security.protocol: SSL
#      zookeeper: localhost:2181
#      schemaRegistry: http://kad-ecs-application-lb-857515197.eu-west-1.elb.amazonaws.com:9000/api/schema-registry
  #    -
  #      name: secondLocal
  #      zookeeper: zookeeper1:2181
  #      bootstrapServers: kafka1:29092
  #      schemaRegistry: http://schemaregistry1:8085
  admin-client-timeout: 5000
zookeeper:
  connection-timeout: 1000
