name: 'Close stale issues'
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          days-before-issue-stale: 7
          days-before-issue-close: 3
          days-before-pr-stale: 7
          days-before-pr-close: 7
          stale-issue-message: 'This issue has been automatically marked as stale because no requested feedback has been provided. It will be closed if no further activity occurs. Thank you for your contributions.'
          stale-pr-message: 'This PR has been automatically marked as stale because no requested changes have been applied. It will be closed if no further activity occurs. Thank you for your contributions.'
          stale-issue-label: 'status/stale'
          stale-pr-label: 'status/stale'
          only-labels: 'status/pending'
          remove-issue-stale-when-updated: true
          labels-to-remove-when-unstale: 'status/pending'
